# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-25 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_item_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='learning_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
