# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-30 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_auto_20200325_1333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='learning_log',
        ),
    ]
